name: Markdown Monitor
on:
  schedule:
    - cron: '0 */12 * * *'  # 每6小时检查一次
  workflow_dispatch:        # 支持手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Clone Target Repo
      run: |
        git clone --depth=1 https://github.com/dw-dengwei/daily-arXiv-ai-enhanced.git target_repo
        # 仅保留Markdown文件
        find target_repo -type f ! -name "*.md" -delete
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Detect Changes
      id: detect_changes
      run: |
        pip install -r requirements.txt
        python scripts/detect_changes.py
        
    - name: Generate RSS
      if: ${{ steps.detect_changes.outputs.has_changes == 'true' }}
      run: |
        python scripts/generate_rss.py '${{ steps.detect_changes.outputs.changed_files }}'
        
    - name: Deploy Feed
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true